config/routes.rb
Rails.application.routes.draw do
  resources :generic_masters

  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'

end

app/models/generic_master.rb
class GenericMaster < ActiveRecord::Base
	enum status: [:active, :inactive]
	validates :name, presence: true

	def self.all_table_names
		['gender', 'language', 'religion']
	end

	def self.all_table_types
		['two_column', 'three_column']
	end

	def is_two_column?
		@generic_master_table_type == self.all_table_types[0]
	end

	def is_three_column?
		@generic_master_table_type == self.all_table_types[1]
	end

	def get_table_name
		return self.table_name
	end

	def get_table_type
		return self.table_type
	end



	# def is_type1?
	# 	GenericMaster.all_types.include? self.type 
	# end

	# def after_initialize
	# 	return unless new_record?
	# 	self.precedence = 0
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def hello
  # 	render text: "hello, World!"
  # end
end

app/controllers/generic_master_controller.rb
class GenericMasterController < ApplicationController
end

app/controllers/generic_masters_controller.rb
class GenericMastersController < ApplicationController
  before_action :set_generic_master, only: [:show, :edit, :update, :destroy]

  # GET /generic_masters
  # GET /generic_masters.json
  def index
    # @generic_masters = GenericMaster.all
    @generic_master_table_name = params[:table_name]
    @generic_master_table_type = params[:table_type]
    @generic_masters = GenericMaster.where(:table_name => params[:table_name])
    # mytemplate = params[:type] + "s"
    # render :template => "generic_masters/#{mytemplate}/index"
    # render :template => "generic_masters/index"
  end

  # GET /generic_masters/1
  # GET /generic_masters/1.json
  def show
  end

  # GET /generic_masters/new
  def new
    @generic_master = GenericMaster.new
    @generic_master.table_name = params[:table_name]
    @generic_master.table_type = params[:table_type]
  end

  # GET /generic_masters/1/edit
  def edit
  end

  # POST /generic_masters
  # POST /generic_masters.json
  def create
    @generic_master = GenericMaster.new(generic_master_params)

    respond_to do |format|
      if @generic_master.save
        format.html { redirect_to @generic_master, notice: "#{@generic_master.table_name.titleize.singularize} was successfully created." }
        format.json { render :show, status: :created, location: @generic_master }
      else
        format.html { render :new }
        format.json { render json: @generic_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generic_masters/1
  # PATCH/PUT /generic_masters/1.json
  def update
    respond_to do |format|
      if @generic_master.update(generic_master_params)
        format.html { redirect_to @generic_master, notice: "#{@generic_master.table_name.titleize.singularize} was successfully updated." }
        format.json { render :show, status: :ok, location: @generic_master }
      else
        format.html { render :edit }
        format.json { render json: @generic_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generic_masters/1
  # DELETE /generic_masters/1.json
  def destroy
    table_name = @generic_master.table_name
    table_type = @generic_master.table_type
    @generic_master.destroy
    respond_to do |format|
      format.html { redirect_to generic_masters_url(:table_name => table_name, :table_type => table_type), notice: "#{@generic_master.table_name.titleize.singularize} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generic_master
      @generic_master = GenericMaster.find(params[:id])
      @generic_master.table_name ||= params[:table_name]
      @generic_master.table_type ||= params[:table_type]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generic_master_params
      params.require(:generic_master).permit(:name, :full_name, :precedence, :table_name, :table_type)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per page basis
	def full_title(page_title = '')
		base_title = 'Ruby on Rails Tutorial Sample App'
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/generic_masters_helper.rb
module GenericMastersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/generic_masters/_form.html.erb
<%= form_for(@generic_master) do |f| %>
  <% if @generic_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generic_master.errors.count, "error") %> prohibited this generic_master from being saved:</h2>

      <ul>
      <% @generic_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <% if @generic_master.table_type == "three_column" %>
    <div class="field">
      <%= f.label :precedence %><br>
      <%= f.number_field :precedence %>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :table_name %><br>
    <%= f.text_field :table_name %>
  </div>
  <div class="field" hidden>
    <%= f.label :table_type %><br>
    <%= f.text_field :table_type %>
  </div>
  <div class="actions">
    <%= f.submit "Create #{@generic_master.table_name.titleize.singularize}" %>
  </div>
<% end %>

app/views/generic_masters/edit.html.erb
<h1>Editing <%= @generic_master.table_name.titleize.singularize %></h1>

<%= render 'form' %>

<%= link_to 'Show', @generic_master %> |
<%= link_to 'Back', generic_masters_path(:table_name => @generic_master.table_name, :table_type => @generic_master.table_type) %>

app/views/generic_masters/genders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Full name</th>
      <th>Precedence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generic_masters.each do |generic_master| %>
      <tr>
        <td><%= generic_master.name %></td>
        <td><%= generic_master.full_name %></td>
        <td><%= generic_master.precedence %></td>
        <td><%= link_to 'Show', generic_master %></td>
        <td><%= link_to 'Edit', edit_generic_master_path(generic_master) %></td>
        <td><%= link_to 'Destroy', generic_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generic master', new_generic_master_path %>

app/views/generic_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=  @generic_master_table_name.titleize.pluralize %> Master Table</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Full name</th>
      <% if @generic_master_table_type == "three_column" %>
        <th>Precedence</th>
      <% end %>
      <th>Table Name</th>
      <th hidden>Table Type</th>
      <th hidden>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generic_masters.each do |generic_master| %>
      <tr>
        <td><%= generic_master.name %></td>
        <td><%= generic_master.full_name %></td>
        <% if @generic_master_table_type == "three_column" %>
          <td><%= generic_master.precedence %></td>
        <% end %>
        <!-- <td><%= hidden_field_tag(generic_master.table_name) %></td> -->
        <td><%= generic_master.table_name %></td>
        <td hidden><%= generic_master.table_type %></td>
        <td hidden><%= generic_master.status %></td>
        <td><%= link_to 'Show', generic_master %></td>
        <td><%= link_to 'Edit', edit_generic_master_path(generic_master, :table_name => generic_master.table_name, :table_type => generic_master.table_type) %></td>
        <td><%= link_to 'Destroy', generic_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New #{@generic_master_table_name.titleize.singularize}", new_generic_master_path(:table_name => @generic_master_table_name, :table_type => @generic_master_table_type) %>

<!-- <p id="notice"><%= notice %></p>

<h1>Listing Generic Masters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Full name</th>
      <th>Precedence</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generic_masters.each do |generic_master| %>
      <tr>
        <td><%= generic_master.name %></td>
        <td><%= generic_master.full_name %></td>
        <td><%= generic_master.precedence %></td>
        <td><%= generic_master.table_type %></td>
        <td><%= link_to 'Show', generic_master %></td>
        <td><%= link_to 'Edit', edit_generic_master_path(generic_master) %></td>
        <td><%= link_to 'Destroy', generic_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generic master', new_generic_master_path %> -->

app/views/generic_masters/new.html.erb
<h1>New <%= @generic_master.table_name.titleize.singularize  %></h1>

<%= render 'form' %>

<%= link_to 'Back', generic_masters_path(:table_name => @generic_master.table_name, :table_type => @generic_master.table_type) %>

app/views/generic_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @generic_master.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @generic_master.full_name %>
</p>

<p>
  <strong>Precedence:</strong>
  <%= @generic_master.precedence %>
</p>

<p>
  <strong>Table Name:</strong>
  <%= @generic_master.table_name %>
</p>

<%= link_to 'Edit', edit_generic_master_path(@generic_master, :table_name => @generic_master.table_name, :table_type => @generic_master.table_type) %> |
<%= link_to 'Back', generic_masters_path(:table_name => @generic_master.table_name, :table_type => @generic_master.table_type) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
	The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a 
	<a href="http://www.railstutorial.org/book">book</a> and
	<a href="http://www.screencasts.railstutorial.org">screencast series</a>
	to teach web development with
	<a href="http://www.rubyonrails.org/">Ruby on Rails</a>.
	This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
	Contact the Ruby on Rails Tutorial about the sample app at the
	<a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at
	<a href="http://www.railstutorial.org/#help">Rails Tutorial Help Section</a>.
	To get help on this app, see the
	<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
	book</a>.
</p>

app/views/static_pages/home.html.erb
<h1>Sample App</h1>
<p>
	This is the Home Page for the
	<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.<br>
	This application is hosted at https://git.heroku.com/cryptic-falls-1314.git
</p>